### ISSUE TITLE
pdstable doesn't parse COISS multi fields correctly 

### ISSUE THREAD

**Issue by basilleaf** [SETI/pds-tools#4]
data gets lost when using pdstable to read multi or list fields for COISS, such as FILTER_NAME.  It only picks up one of the filters in the list of two. The LBL file does appear to define the field correctly wrt start_byte/bytes as found in the .tab file. 

from pdstable import PdsTable

db_columns = ['FILTER_NAME', 'FILE_SPECIFICATION_NAME']
label_file = '/volumes/COISS_2xxx/COISS_2104/index/index.lbl'

table = PdsTable(label_file, columns=db_columns)
table_rows = table.dicts_by_row()

print table_rows

**Comment by basilleaf** [comment]
I did not have much luck trying to debug pdstable.py. It's somewhere near: # Handle the optional case of multiple items per column. 

It seems like the variable dtype0 is created to hold info about how to read the multi fields, but I couldn't really tell where or if it's implemented.

**Comment by markshowalter** [comment]
I forgot about this also but can take a look this week.

Lisa--please point me to a file that cannot be read.

--Mark

**Comment by basilleaf** [comment]
@markshowalter label_file = '/volumes/COISS_2xxx/COISS_2104/index/index.lbl' (see issue description for how to reproduce https://github.com/SETI/pds-tools/issues/4)

**Comment by markshowalter** [comment]
Lisa,

I fixed the bug that came up in the COISS index files, causing the second filter name to be missed. I will check in my changes when I get a chance. (I'm on an airplane now and for most of the day.)

The COVIMS issue is different. There appear to be syntax errors in every COVIMS index label. This is annoying but not at all uncommon. It's one of the reasons PDS is moving to the PDS4 standard and XML labels, where syntax checking is built in.

The errors are these:

Line 17 is a comment but is not delimited by /* and */

On line 131, the word "OFF", including the quotes, is embedded inside a DESCRIPTION field that is already quoted.

If you edit the label to fix these errors, everything works.

My plan is to fix our local copies of the VIMS index files, which we maintain in our "metadata" directory tree on line. We generally don't change files in the volumes directories because they are produced by others--although I have made some exceptions in the past.

For now, you can either edit the labels or wait for my revisions to show up online. In the future, you should probably load the OPUS database from our metadata/ directory tree rather than from our volumes/ tree.

--Mark

On Oct 19, 2017, at 1:34 PM, Lisa Ballard <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #4<https://github.com/SETI/pds-tools/issues/4>.
